// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from '@prismicio/client';

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship['fields'][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship['id']]: ContentRelationshipFieldWithData<
      TSubRelationship['customtypes'],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship['fields'][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup['id']]: TData[TGroup['id']] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship['fields'][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >['id']]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>['data'],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>['id']];

type PageDocumentDataSlicesSlice =
  | HeadlineFormImageSplitSlice
  | TextImageCtaSlice
  | FounderIntroSlice
  | ImageStackSlice
  | ProcessStepsSlice
  | CenteredIntroWithFeatureTagsSlice
  | HeroSlice
  | RichTextSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Title field in *Page*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, 'page', Lang>;

/**
 * Content for Settings documents
 */
interface SettingsDocumentData {
  /**
   * Site Title field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.site_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  site_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.meta_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.meta_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Navigation field in *Settings*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.navigation
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  navigation: prismic.Repeatable<
    prismic.LinkField<
      string,
      string,
      unknown,
      prismic.FieldState,
      'Link' | 'Button'
    >
  >;
}

/**
 * Settings document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SettingsDocumentData>,
    'settings',
    Lang
  >;

export type AllDocumentTypes = PageDocument | SettingsDocument;

/**
 * Item in *CenteredIntroWithFeatureTags → Default → Primary → Feature Tags*
 */
export interface CenteredIntroWithFeatureTagsSliceDefaultPrimaryFeatureTagsItem {
  /**
   * Icon field in *CenteredIntroWithFeatureTags → Default → Primary → Feature Tags*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: centered_intro_with_feature_tags.default.primary.feature_tags[].icon
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  icon: prismic.ImageField<never>;

  /**
   * Label field in *CenteredIntroWithFeatureTags → Default → Primary → Feature Tags*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: centered_intro_with_feature_tags.default.primary.feature_tags[].label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label: prismic.KeyTextField;
}

/**
 * Primary content in *CenteredIntroWithFeatureTags → Default → Primary*
 */
export interface CenteredIntroWithFeatureTagsSliceDefaultPrimary {
  /**
   * Title field in *CenteredIntroWithFeatureTags → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: centered_intro_with_feature_tags.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Feature Tags field in *CenteredIntroWithFeatureTags → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: centered_intro_with_feature_tags.default.primary.feature_tags[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  feature_tags: prismic.GroupField<
    Simplify<CenteredIntroWithFeatureTagsSliceDefaultPrimaryFeatureTagsItem>
  >;
}

/**
 * Default variation for CenteredIntroWithFeatureTags Slice
 *
 * - **API ID**: `default`
 * - **Description**: Centered headline and secondary text with floating feature tags/icons placed around the section.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CenteredIntroWithFeatureTagsSliceDefault =
  prismic.SharedSliceVariation<
    'default',
    Simplify<CenteredIntroWithFeatureTagsSliceDefaultPrimary>,
    never
  >;

/**
 * Slice variation for *CenteredIntroWithFeatureTags*
 */
type CenteredIntroWithFeatureTagsSliceVariation =
  CenteredIntroWithFeatureTagsSliceDefault;

/**
 * CenteredIntroWithFeatureTags Shared Slice
 *
 * - **API ID**: `centered_intro_with_feature_tags`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CenteredIntroWithFeatureTagsSlice = prismic.SharedSlice<
  'centered_intro_with_feature_tags',
  CenteredIntroWithFeatureTagsSliceVariation
>;

/**
 * Primary content in *FounderIntro → Default → Primary*
 */
export interface FounderIntroSliceDefaultPrimary {
  /**
   * Portrait field in *FounderIntro → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: founder_intro.default.primary.portrait
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  portrait: prismic.ImageField<never>;

  /**
   * Name field in *FounderIntro → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: founder_intro.default.primary.name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  name: prismic.KeyTextField;

  /**
   * Role field in *FounderIntro → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: founder_intro.default.primary.role
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  role: prismic.KeyTextField;

  /**
   * Intro Title field in *FounderIntro → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: founder_intro.default.primary.intro_title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  intro_title: prismic.RichTextField;

  /**
   * Intro Text field in *FounderIntro → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: founder_intro.default.primary.intro_text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  intro_text: prismic.RichTextField;

  /**
   * Contact Links field in *FounderIntro → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: founder_intro.default.primary.contact_links
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  contact_links: prismic.Repeatable<
    prismic.LinkField<
      string,
      string,
      unknown,
      prismic.FieldState,
      'instagram' | 'linkedin' | 'email' | 'phone'
    >
  >;

  /**
   * Content field in *FounderIntro → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: founder_intro.default.primary.content
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  content: prismic.RichTextField;

  /**
   * CTA Button field in *FounderIntro → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: founder_intro.default.primary.cta_button
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  cta_button: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Default variation for FounderIntro Slice
 *
 * - **API ID**: `default`
 * - **Description**: Standard founder introduction with photo, bio, description, contact/social links, and CTA.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FounderIntroSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<FounderIntroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *FounderIntro*
 */
type FounderIntroSliceVariation = FounderIntroSliceDefault;

/**
 * FounderIntro Shared Slice
 *
 * - **API ID**: `founder_intro`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FounderIntroSlice = prismic.SharedSlice<
  'founder_intro',
  FounderIntroSliceVariation
>;

/**
 * Primary content in *ContactSection → Default → Primary*
 */
export interface HeadlineFormImageSplitSliceDefaultPrimary {
  /**
   * Subtitle field in *ContactSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: headline_form_image_split.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  subtitle: prismic.RichTextField;

  /**
   * Title field in *ContactSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: headline_form_image_split.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Form title field in *ContactSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: headline_form_image_split.default.primary.form_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  form_title: prismic.KeyTextField;

  /**
   * Form content field in *ContactSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: headline_form_image_split.default.primary.form_content
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  form_content: prismic.RichTextField;

  /**
   * Button Text field in *ContactSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: headline_form_image_split.default.primary.button_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  button_text: prismic.KeyTextField;

  /**
   * Form image field in *ContactSection → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: headline_form_image_split.default.primary.form_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  form_image: prismic.ImageField<never>;
}

/**
 * Default variation for ContactSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Standard layout with content, form inputs, submit button, and image side by side.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeadlineFormImageSplitSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<HeadlineFormImageSplitSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ContactSection*
 */
type HeadlineFormImageSplitSliceVariation = HeadlineFormImageSplitSliceDefault;

/**
 * ContactSection Shared Slice
 *
 * - **API ID**: `headline_form_image_split`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeadlineFormImageSplitSlice = prismic.SharedSlice<
  'headline_form_image_split',
  HeadlineFormImageSplitSliceVariation
>;

/**
 * Item in *Hero → Default → Primary → Agenda*
 */
export interface HeroSliceDefaultPrimaryAgendaItem {
  /**
   * Plekken beschikbaar? field in *Hero → Default → Primary → Agenda*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: hero.default.primary.agenda[].open
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  open: prismic.BooleanField;

  /**
   * Spots available field in *Hero → Default → Primary → Agenda*
   *
   * - **Field Type**: Number
   * - **Placeholder**: 2
   * - **API ID Path**: hero.default.primary.agenda[].spots_available
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  spots_available: prismic.NumberField;

  /**
   * Spots text field in *Hero → Default → Primary → Agenda*
   *
   * - **Field Type**: Text
   * - **Placeholder**: plekken
   * - **API ID Path**: hero.default.primary.agenda[].spots_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  spots_text: prismic.KeyTextField;
}

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Heading field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Subtitle field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  subtitle: prismic.RichTextField;

  /**
   * CTAs field in *Hero → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.ctas
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  ctas: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;

  /**
   * Agenda field in *Hero → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.agenda[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  agenda: prismic.GroupField<Simplify<HeroSliceDefaultPrimaryAgendaItem>>;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSlice = prismic.SharedSlice<'hero', HeroSliceVariation>;

/**
 * Item in *ImageStack → Default → Primary → Images*
 */
export interface ImageStackSliceDefaultPrimaryImagesItem {
  /**
   * Image field in *ImageStack → Default → Primary → Images*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image_stack.default.primary.images[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;
}

/**
 * Item in *ImageStack → Default → Primary → Marquee items*
 */
export interface ImageStackSliceDefaultPrimaryMarqueeItemsItem {
  /**
   * Marquee text field in *ImageStack → Default → Primary → Marquee items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_stack.default.primary.marquee_items[].marquee_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  marquee_text: prismic.KeyTextField;
}

/**
 * Primary content in *ImageStack → Default → Primary*
 */
export interface ImageStackSliceDefaultPrimary {
  /**
   * Images field in *ImageStack → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: image_stack.default.primary.images[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  images: prismic.GroupField<Simplify<ImageStackSliceDefaultPrimaryImagesItem>>;

  /**
   * Marquee items field in *ImageStack → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: image_stack.default.primary.marquee_items[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  marquee_items: prismic.GroupField<
    Simplify<ImageStackSliceDefaultPrimaryMarqueeItemsItem>
  >;
}

/**
 * Default variation for ImageStack Slice
 *
 * - **API ID**: `default`
 * - **Description**: Standard image stack with visual overlapping.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ImageStackSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<ImageStackSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ImageStack*
 */
type ImageStackSliceVariation = ImageStackSliceDefault;

/**
 * ImageStack Shared Slice
 *
 * - **API ID**: `image_stack`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ImageStackSlice = prismic.SharedSlice<
  'image_stack',
  ImageStackSliceVariation
>;

/**
 * Item in *ProcessSteps → Cards with Numbers → Primary → Steps*
 */
export interface ProcessStepsSliceCardsWithNumbersPrimaryStepsItem {
  /**
   * Step Title field in *ProcessSteps → Cards with Numbers → Primary → Steps*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: process_steps.cards_with_numbers.primary.steps[].step_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  step_title: prismic.KeyTextField;

  /**
   * Step Description field in *ProcessSteps → Cards with Numbers → Primary → Steps*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: process_steps.cards_with_numbers.primary.steps[].step_description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  step_description: prismic.RichTextField;
}

/**
 * Primary content in *ProcessSteps → Cards with Numbers → Primary*
 */
export interface ProcessStepsSliceCardsWithNumbersPrimary {
  /**
   * Eyebrow field in *ProcessSteps → Cards with Numbers → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: process_steps.cards_with_numbers.primary.eyebrow
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  eyebrow: prismic.KeyTextField;

  /**
   * Title field in *ProcessSteps → Cards with Numbers → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: process_steps.cards_with_numbers.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Steps field in *ProcessSteps → Cards with Numbers → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: process_steps.cards_with_numbers.primary.steps[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  steps: prismic.GroupField<
    Simplify<ProcessStepsSliceCardsWithNumbersPrimaryStepsItem>
  >;

  /**
   * Call To Action field in *ProcessSteps → Cards with Numbers → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: process_steps.cards_with_numbers.primary.cta
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  cta: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Cards with Numbers variation for ProcessSteps Slice
 *
 * - **API ID**: `cards_with_numbers`
 * - **Description**: Displays each process step in a numbered card format with the option for step titles and descriptions, a heading, optional eyebrow, and a single call-to-action button.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ProcessStepsSliceCardsWithNumbers = prismic.SharedSliceVariation<
  'cards_with_numbers',
  Simplify<ProcessStepsSliceCardsWithNumbersPrimary>,
  never
>;

/**
 * Slice variation for *ProcessSteps*
 */
type ProcessStepsSliceVariation = ProcessStepsSliceCardsWithNumbers;

/**
 * ProcessSteps Shared Slice
 *
 * - **API ID**: `process_steps`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ProcessStepsSlice = prismic.SharedSlice<
  'process_steps',
  ProcessStepsSliceVariation
>;

/**
 * Primary content in *RichText → Default → Primary*
 */
export interface RichTextSliceDefaultPrimary {
  /**
   * Content field in *RichText → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Lorem ipsum...
   * - **API ID Path**: rich_text.default.primary.content
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  content: prismic.RichTextField;
}

/**
 * Default variation for RichText Slice
 *
 * - **API ID**: `default`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type RichTextSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<RichTextSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *RichText*
 */
type RichTextSliceVariation = RichTextSliceDefault;

/**
 * RichText Shared Slice
 *
 * - **API ID**: `rich_text`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type RichTextSlice = prismic.SharedSlice<
  'rich_text',
  RichTextSliceVariation
>;

/**
 * Primary content in *TextImageCta → Left Text, Right Image → Primary*
 */
export interface TextImageCtaSliceDefaultLeftTextRightImagePrimary {
  /**
   * Content field in *TextImageCta → Left Text, Right Image → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_image_cta.default_left_text_right_image.primary.content
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  content: prismic.RichTextField;

  /**
   * Call to Action field in *TextImageCta → Left Text, Right Image → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: text_image_cta.default_left_text_right_image.primary.cta
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  cta: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Image field in *TextImageCta → Left Text, Right Image → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: text_image_cta.default_left_text_right_image.primary.media
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  media: prismic.ImageField<never>;
}

/**
 * Left Text, Right Image variation for TextImageCta Slice
 *
 * - **API ID**: `default_left_text_right_image`
 * - **Description**: Displays text content and button on the left, with an image on the right.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TextImageCtaSliceDefaultLeftTextRightImage =
  prismic.SharedSliceVariation<
    'default_left_text_right_image',
    Simplify<TextImageCtaSliceDefaultLeftTextRightImagePrimary>,
    never
  >;

/**
 * Slice variation for *TextImageCta*
 */
type TextImageCtaSliceVariation = TextImageCtaSliceDefaultLeftTextRightImage;

/**
 * TextImageCta Shared Slice
 *
 * - **API ID**: `text_image_cta`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TextImageCtaSlice = prismic.SharedSlice<
  'text_image_cta',
  TextImageCtaSliceVariation
>;

declare module '@prismicio/client' {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      SettingsDocument,
      SettingsDocumentData,
      AllDocumentTypes,
      CenteredIntroWithFeatureTagsSlice,
      CenteredIntroWithFeatureTagsSliceDefaultPrimaryFeatureTagsItem,
      CenteredIntroWithFeatureTagsSliceDefaultPrimary,
      CenteredIntroWithFeatureTagsSliceVariation,
      CenteredIntroWithFeatureTagsSliceDefault,
      FounderIntroSlice,
      FounderIntroSliceDefaultPrimary,
      FounderIntroSliceVariation,
      FounderIntroSliceDefault,
      HeadlineFormImageSplitSlice,
      HeadlineFormImageSplitSliceDefaultPrimary,
      HeadlineFormImageSplitSliceVariation,
      HeadlineFormImageSplitSliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimaryAgendaItem,
      HeroSliceDefaultPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      ImageStackSlice,
      ImageStackSliceDefaultPrimaryImagesItem,
      ImageStackSliceDefaultPrimaryMarqueeItemsItem,
      ImageStackSliceDefaultPrimary,
      ImageStackSliceVariation,
      ImageStackSliceDefault,
      ProcessStepsSlice,
      ProcessStepsSliceCardsWithNumbersPrimaryStepsItem,
      ProcessStepsSliceCardsWithNumbersPrimary,
      ProcessStepsSliceVariation,
      ProcessStepsSliceCardsWithNumbers,
      RichTextSlice,
      RichTextSliceDefaultPrimary,
      RichTextSliceVariation,
      RichTextSliceDefault,
      TextImageCtaSlice,
      TextImageCtaSliceDefaultLeftTextRightImagePrimary,
      TextImageCtaSliceVariation,
      TextImageCtaSliceDefaultLeftTextRightImage,
    };
  }
}
