// Code generated by Slice Machine. DO NOT EDIT.

import { defineAsyncComponent } from "vue";
import { defineSliceZoneComponents } from "@prismicio/vue";

export const components = defineSliceZoneComponents({
  centered_intro_with_feature_tags: defineAsyncComponent(
    () => import("./CenteredIntroWithFeatureTags/index.vue"),
  ),
  hero: defineAsyncComponent(() => import("./Hero/index.vue")),
  process_steps: defineAsyncComponent(() => import("./ProcessSteps/index.vue")),
  rich_text: defineAsyncComponent(() => import("./RichText/index.vue")),
});
